#!/bin/bash

input_file=/etc/openvpn/openvpn-status.log

echo ""

echo "Reading $input_file"

echo ""

while read line; do

    if [[ "$line" = *,* ]]; then

        IFS=',' read -ra fields <<< "$line"    #Convert string to array

        if [[ "${fields[1]}" =~ \.[0-9]{1,3}:[0-9] ]]; then

                received=$((fields[2] / 2**20))

                sent=$((fields[3] / 2**20))

                echo "User:  ${fields[0]} from ${fields[1]}"

                echo "Since: ${fields[4]}"

                echo "Rcvd:  ${received} MB"

                echo "Sent:  ${sent} MB"

                echo ""

        fi

    fi

done < $input_file

echo ""

echo "Done reading $input_file"

echo "" Detalhes
