#!/bin/bash

clear
echo "Edited by @ColtSeals"
red='\e[1;31m'
green='\e[0;32m'
NC='\e[0m'
echo "Conectando ao NerdologiaVPS..."
sleep 0.4
echo "Checando Permissão..."
sleep 0.2
echo -e "${green}Permissão Aceita...${NC}"
sleep 0.2

clear
while true; do
echo -e "\033[1;37m •••••••••••••••••••••••••••••••••••••••••••••••••••••••\033[0m"
tput setaf 7 ; tput setab 4 ; tput bold ; printf '%35s%s%-20s\n' " MONITOR OpenVPN " ; tput sgr0
echo -e "\033[1;37m •••••••••••••••••••••••••••••••••••••••••••••••••••••••\033[0m"
echo -e "\033[1;37m •••••••••••••••••••••••••••••••••••••••••••••••••••••••\033[0m"
echo -e " \033[47;30m    Usuario                    Conectado       Status \033[0m"
echo -e "\033[1;37m •••••••••••••••••••••••••••••••••••••••••••••••••••••••\033[0m"
for _user in $(awk -F: '$3>=1000 {print $1}' /etc/passwd); do
if [[ ! -z $(cat /etc/openvpn/*.log|grep ,${_user},) ]]; then
_conn=$(cat /etc/openvpn/*.log|grep ,${_user},| wc -l)
on="0"
else 
on="1"
fi
_user=$(printf '%-18s' "$us1")
cnx=$(printf '%-10s' "$on")
echo -e "\033[1;33m  $_user               $_conn              $cnx       \033[0m"
echo -e "\033[1;37m ------------------------------------------------------\033[0m"
fi
done
sleep 5
clear
done
